import { Module } from '@nestjs/common';
import { ShopController } from './shop.controller';
import { ShopService } from './shop.service';

// Automatically generated by "yarn nestgen module shop"

@Module({
  // imports: [] <--- you can put other modules as imports, and this will make the exports of other modules available to be injected into the constructors/services
  controllers: [ShopController], // Controllers go here, otherwise they will not be available as routes
  providers: [ShopService] // Non-controller classes that provide support go here. For our project, for the most part, the Service classes deal with MongoDB
})
export class ShopModule {}
